/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.HeadlessException;
import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author e1ghtSpace
 */
public class PEncodePlusUI extends javax.swing.JFrame {

    /**
     * Creates new form PEncodePlusUI
     */
    public PEncodePlusUI() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblEncode = new javax.swing.JLabel();
        jPnlEncode = new javax.swing.JPanel();
        jLblEncFile = new javax.swing.JLabel();
        jTxtEncFile = new javax.swing.JTextField();
        jBtnEncBrowse = new javax.swing.JButton();
        jLblEncWidth = new javax.swing.JLabel();
        jTxtEncWidth = new javax.swing.JTextField();
        jLblEncHeight = new javax.swing.JLabel();
        jTxtEncHeight = new javax.swing.JTextField();
        jLblEncOutput = new javax.swing.JLabel();
        jTxtEncOutFloc = new javax.swing.JTextField();
        jBtnEncOutBrowse = new javax.swing.JButton();
        jBtnEncode = new javax.swing.JButton();
        jPnlDecode = new javax.swing.JPanel();
        jLblDecInput = new javax.swing.JLabel();
        jTxtDecInputFldr = new javax.swing.JTextField();
        jLblDecOutput = new javax.swing.JLabel();
        jTxtDecOutputFldr = new javax.swing.JTextField();
        jBtnDecInputBrowse = new javax.swing.JButton();
        jBtnDecOutputBrowse = new javax.swing.JButton();
        jBtnDecode = new javax.swing.JButton();
        jLblDecode = new javax.swing.JLabel();
        jProgressBar = new javax.swing.JProgressBar();
        jSepEncDec = new javax.swing.JSeparator();
        jSepDecPrgBar = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PEncode+");
        setResizable(false);
        setSize(new java.awt.Dimension(400, 400));

        jLblEncode.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLblEncode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblEncode.setText("Encode");

        jPnlEncode.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLblEncFile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLblEncFile.setText("File:");

        jTxtEncFile.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jTxtEncFile.setText("File Location");

        jBtnEncBrowse.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jBtnEncBrowse.setText("Browse");
        jBtnEncBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEncBrowseActionPerformed(evt);
            }
        });

        jLblEncWidth.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLblEncWidth.setText("Width:");

        jTxtEncWidth.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jTxtEncWidth.setText("512");

        jLblEncHeight.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLblEncHeight.setText("Height:");

        jTxtEncHeight.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jTxtEncHeight.setText("512");

        jLblEncOutput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLblEncOutput.setText("Output Folder:");

        jTxtEncOutFloc.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jTxtEncOutFloc.setText("Folder Location");

        jBtnEncOutBrowse.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jBtnEncOutBrowse.setText("Browse");
        jBtnEncOutBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEncOutBrowseActionPerformed(evt);
            }
        });

        jBtnEncode.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBtnEncode.setText("Encode");

        javax.swing.GroupLayout jPnlEncodeLayout = new javax.swing.GroupLayout(jPnlEncode);
        jPnlEncode.setLayout(jPnlEncodeLayout);
        jPnlEncodeLayout.setHorizontalGroup(
            jPnlEncodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlEncodeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlEncodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnEncode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPnlEncodeLayout.createSequentialGroup()
                        .addComponent(jLblEncWidth)
                        .addGap(14, 14, 14)
                        .addComponent(jTxtEncWidth))
                    .addGroup(jPnlEncodeLayout.createSequentialGroup()
                        .addComponent(jLblEncFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtEncFile, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(jBtnEncBrowse))
                    .addGroup(jPnlEncodeLayout.createSequentialGroup()
                        .addComponent(jLblEncOutput)
                        .addGap(10, 10, 10)
                        .addComponent(jTxtEncOutFloc, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnEncOutBrowse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPnlEncodeLayout.createSequentialGroup()
                        .addComponent(jLblEncHeight)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtEncHeight)))
                .addContainerGap())
        );
        jPnlEncodeLayout.setVerticalGroup(
            jPnlEncodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlEncodeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlEncodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblEncFile)
                    .addComponent(jTxtEncFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnEncBrowse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlEncodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblEncWidth)
                    .addComponent(jTxtEncWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlEncodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblEncHeight)
                    .addComponent(jTxtEncHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlEncodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblEncOutput)
                    .addComponent(jTxtEncOutFloc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnEncOutBrowse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnEncode)
                .addContainerGap())
        );

        jLblDecInput.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLblDecInput.setText("Input Folder:");

        jTxtDecInputFldr.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jTxtDecInputFldr.setText("Folder Location");

        jLblDecOutput.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLblDecOutput.setText("Output Folder:");

        jTxtDecOutputFldr.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jTxtDecOutputFldr.setText("Folder Location");

        jBtnDecInputBrowse.setText("Browse");
        jBtnDecInputBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDecInputBrowseActionPerformed(evt);
            }
        });

        jBtnDecOutputBrowse.setText("Browse");
        jBtnDecOutputBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDecOutputBrowseActionPerformed(evt);
            }
        });

        jBtnDecode.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jBtnDecode.setText("Decode");

        javax.swing.GroupLayout jPnlDecodeLayout = new javax.swing.GroupLayout(jPnlDecode);
        jPnlDecode.setLayout(jPnlDecodeLayout);
        jPnlDecodeLayout.setHorizontalGroup(
            jPnlDecodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlDecodeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlDecodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnDecode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPnlDecodeLayout.createSequentialGroup()
                        .addGroup(jPnlDecodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblDecOutput)
                            .addComponent(jLblDecInput))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPnlDecodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtDecInputFldr)
                            .addComponent(jTxtDecOutputFldr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPnlDecodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBtnDecInputBrowse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnDecOutputBrowse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPnlDecodeLayout.setVerticalGroup(
            jPnlDecodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlDecodeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlDecodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblDecInput)
                    .addComponent(jTxtDecInputFldr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnDecInputBrowse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlDecodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblDecOutput)
                    .addComponent(jTxtDecOutputFldr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnDecOutputBrowse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnDecode)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLblDecode.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLblDecode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblDecode.setText("Decode");

        jProgressBar.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSepEncDec)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblEncode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPnlEncode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPnlDecode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLblDecode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSepDecPrgBar, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblEncode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPnlEncode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSepEncDec, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLblDecode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPnlDecode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSepDecPrgBar, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnEncBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEncBrowseActionPerformed
        // TODO add your handling code here:
            try
        {
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            int returnValue = fileChooser.showOpenDialog(null);

            jTxtEncFile.setText(fileChooser.getSelectedFile().getAbsolutePath());
        }
        catch(HeadlessException ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jBtnEncBrowseActionPerformed

    private void jBtnEncOutBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEncOutBrowseActionPerformed
        // TODO add your handling code here:
                    try
        {
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            int returnValue = fileChooser.showOpenDialog(null);

            jTxtEncOutFloc.setText(fileChooser.getSelectedFile().getAbsolutePath());
        }
        catch(HeadlessException ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jBtnEncOutBrowseActionPerformed

    private void jBtnDecInputBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDecInputBrowseActionPerformed
        // TODO add your handling code here:
                    try
        {
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            int returnValue = fileChooser.showOpenDialog(null);

            jTxtDecInputFldr.setText(fileChooser.getSelectedFile().getAbsolutePath());
        }
        catch(HeadlessException ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jBtnDecInputBrowseActionPerformed

    private void jBtnDecOutputBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDecOutputBrowseActionPerformed
        // TODO add your handling code here:
                    try
        {
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            int returnValue = fileChooser.showOpenDialog(null);

            jTxtDecOutputFldr.setText(fileChooser.getSelectedFile().getAbsolutePath());
        }
        catch(HeadlessException ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jBtnDecOutputBrowseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PEncodePlusUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PEncodePlusUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PEncodePlusUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PEncodePlusUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PEncodePlusUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnDecInputBrowse;
    private javax.swing.JButton jBtnDecOutputBrowse;
    private javax.swing.JButton jBtnDecode;
    private javax.swing.JButton jBtnEncBrowse;
    private javax.swing.JButton jBtnEncOutBrowse;
    private javax.swing.JButton jBtnEncode;
    private javax.swing.JLabel jLblDecInput;
    private javax.swing.JLabel jLblDecOutput;
    private javax.swing.JLabel jLblDecode;
    private javax.swing.JLabel jLblEncFile;
    private javax.swing.JLabel jLblEncHeight;
    private javax.swing.JLabel jLblEncOutput;
    private javax.swing.JLabel jLblEncWidth;
    private javax.swing.JLabel jLblEncode;
    private javax.swing.JPanel jPnlDecode;
    private javax.swing.JPanel jPnlEncode;
    private javax.swing.JProgressBar jProgressBar;
    private javax.swing.JSeparator jSepDecPrgBar;
    private javax.swing.JSeparator jSepEncDec;
    private javax.swing.JTextField jTxtDecInputFldr;
    private javax.swing.JTextField jTxtDecOutputFldr;
    private javax.swing.JTextField jTxtEncFile;
    private javax.swing.JTextField jTxtEncHeight;
    private javax.swing.JTextField jTxtEncOutFloc;
    private javax.swing.JTextField jTxtEncWidth;
    // End of variables declaration//GEN-END:variables
}
